import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AppBar from '../components/appbar';

export default function Home({ data }) {

  console.log(data.data[0]);
  // Make a style to center the elements inside 
  const styleCenter = {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    flexWrap: 'wrap',
    color: 'white',
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>CryptoWatchers - Dashboard de cryptos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AppBar></AppBar>
      <main className={styles.main}>
        <h2 style={{ marginTop: '1.5rem' }}><b>Principais cryptos: </b></h2>
        <div style={{ ...styleCenter, marginTop: '1rem' }}>
          {data.data.slice(0, 20).map(item => (
            <div className={styles.glass} key={`Item__${item.id}`}>
              <h3>{item.name} ({item.symbol})</h3>
              <p>$ {parseFloat(item.priceUsd)}</p>
              <p style={{ color: (item.changePercent24Hr > 0) ? 'green' : 'red', }}>
                {parseFloat(item.changePercent24Hr).toFixed(2)} %
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' GRPG'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch('https://api.coincap.io/v2/assets');
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
